CREATE TABLE `USER_LIST` (
 `CIF` int(11) NOT NULL AUTO_INCREMENT,
 `EMAIL` varchar(50) COLLATE utf8_bin NOT NULL,
 `PASSWORD` char(130) COLLATE utf8_bin NOT NULL,
 `DISPLAY_NAME` varchar(16) COLLATE utf8_bin NOT NULL,
 `ROLE` int(11) NOT NULL,
 `REFRESH_TOKEN` char(32) NOT NULL,
 `LAST_LOGIN_DATE` DATETIME NOT NULL,
 `REGISTER_DATE` DATETIME NOT NULL,
 UNIQUE KEY `USER_LIST_CIF` (`CIF`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
